# Generated by Django 4.2.5 on 2024-01-26 13:13

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'appcpt_departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cedula', models.CharField(max_length=45)),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.departamento')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CentroCostos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCurricular',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dedicacion', models.IntegerField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('vinculacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.vinculacion')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('codigo', models.IntegerField()),
                ('numero_horas', models.DecimalField(decimal_places=0, max_digits=20)),
                ('nivel', models.CharField(max_length=45)),
                ('proyecto_curricular', models.CharField(max_length=45)),
                ('grupo', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('horario', models.CharField(max_length=90)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadInvestigativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_actividad_investigativa', models.CharField(max_length=100)),
                ('funcion', models.CharField(max_length=45)),
                ('acta_facultad', models.CharField(max_length=15)),
                ('titulo_proyecto', models.CharField(max_length=200)),
                ('horas_semanales', models.IntegerField()),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.centrocostos')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.nivel')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.profesor')),
                ('proyecto_curricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.proyectocurricular')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadGestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actividad_gestion', models.IntegerField()),
                ('horas_semana', models.IntegerField()),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.centrocostos')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadExtension',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('coidgo', models.IntegerField()),
                ('horas_semanales', models.IntegerField(db_column='horas_semanales')),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.centrocostos')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ActividadDocente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_estudiantes', models.IntegerField()),
                ('horas_curso', models.IntegerField()),
                ('tutorias_estudiantes_horas', models.IntegerField()),
                ('preparacion_horas', models.IntegerField()),
                ('evaluacion_horas', models.IntegerField()),
                ('centro_costos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.centrocostos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.curso')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.nivel')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.periodoacademico')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.profesor')),
                ('proyecto_curricular', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.proyectocurricular')),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.facultad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appCPT.rol'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
